### ISSUE TITLE
Need more explanation of what each rake task is for

### ISSUE THREAD

**Issue by andrewhavens** [HipByte/motion-fabric#1]
I was able to follow the configuration steps to get Fabric/Crashlytics installed. Now I'm trying to get a better understanding of the rake tasks and how they work so that I can integrate it into my build process. Currently, I use another crash reporting service, and I upload the dDSYM every time I build the app (even in development when using the simulator). There are several rake tasks mentioned in the readme: `fabric:setup`, `fabric:dsym:device`, `fabric:upload`. It's not clear to me which of these tasks I would need to use in order to upload my simulator dSYM. Some additional documentation (or clarification) would be helpful.

**Comment by MarkVillacampa** [comment]
Hello Andrew,

I have improved the documentation with this commit: c8b2cb1478ed7cd57aa07f54882e5a0c3925e9f0

Do you have any other suggestions to improve the documentation?

**Comment by andrewhavens** [comment]
Thanks! That helps. I think that was a nice improvement.

I think another thing that was confusing to me is when you mention "Beta builds" or crashlytics beta, or fabric beta. I think I understand now that "Beta" is the name of a feature of Fabric. I don't know much about it, so it was not clear what kinds of builds were considered "beta" builds, since I wouldn't think they would be any different from `archive:release` builds. The way that I was reading the documentation was that you could opt into a "pre-release" version of their SDK. So maybe it would be helpful to briefly mention that beta is an optional feature for distributing your app to testers.

**Comment by MarkVillacampa** [comment]
I think eeea23bb6d36797135ab632b14050e319e38ec96 should fix the confusing wording and add more explanations.

Thanks for your suggestions!

PD: Im going to close the issue for now, but feel free to comment here again or open another issue.
